#include "duke3d.h"
#include "gametypes.h"

Gametype_t Gametypes[MAXGAMETYPES] = {
    "DUKEMATCH",      GAMETYPE_FRAGBAR | GAMETYPE_SCORESHEET | GAMETYPE_DMSWITCHES | GAMETYPE_ALLOWITEMRESPAWN | GAMETYPE_MARKEROPTION | GAMETYPE_ACCESSATSTART,
    "COOPERATIVE",    GAMETYPE_COOP | GAMETYPE_COOPSPAWN | GAMETYPE_WEAPSTAY | GAMETYPE_ACCESSCARDSPRITES | GAMETYPE_COOPVIEW | GAMETYPE_COOPSOUND | GAMETYPE_OTHERPLAYERSINMAP | GAMETYPE_MARKEROPTION | GAMETYPE_ALLOWITEMRESPAWN | GAMETYPE_PLAYERSFRIENDLY | GAMETYPE_FIXEDRESPAWN | GAMETYPE_PRESERVEINVENTORYEOL,
    "TEAM DUKEMATCH", GAMETYPE_FRAGBAR | GAMETYPE_SCORESHEET | GAMETYPE_DMSWITCHES | GAMETYPE_ALLOWITEMRESPAWN | GAMETYPE_MARKEROPTION | GAMETYPE_ACCESSATSTART | GAMETYPE_TDM | GAMETYPE_TDMSPAWN,
    "SURVIVAL",       GAMETYPE_COOP | GAMETYPE_COOPSPAWN | GAMETYPE_WEAPSTAY | GAMETYPE_ACCESSCARDSPRITES | GAMETYPE_COOPVIEW | GAMETYPE_COOPSOUND | GAMETYPE_OTHERPLAYERSINMAP | GAMETYPE_MARKEROPTION | GAMETYPE_ALLOWITEMRESPAWN | GAMETYPE_PLAYERSFRIENDLY | GAMETYPE_FIXEDRESPAWN | GAMETYPE_PRESERVEINVENTORYEOL | GAMETYPE_LIMITEDLIVES,
};
uint8_t g_numGametypes = 4;

uint8_t numTeams = 4;
// No sense having more teams than you can have players.
Team_t teams[MAXPLAYERS] = {
    { "Blue", 9, 0, 0, 0 },
    { "Red", 10, 0, 0, 0 },
    { "Green", 11, 0, 0, 0 },
    { "Gray", 12, 0, 0, 0 },
};
